name: ⚡️ Video CompressorX ⚡️

on:

  schedule:

    - cron: "0 */2 * * *"

  workflow_dispatch:

jobs:

  update:

    runs-on: ubuntu-latest

    steps:

      - name: 🐍 Set up Python 3.9 🐍

        uses: actions/setup-python@v2

        with:

          python-version: 3.9

      - name: 🌀 Clone the Repo 🌀

        uses: actions/checkout@master

        with:

          repository: ${{ secrets.REPO_NAME }}

      - name: 📀 Install dependencies. 📀

        run: |

          pip install TgCrypto https://raw.githubusercontent.com/HasibulKabir/pyrogramarchive/master/pyrogramasyncv0.18.0.zip git+https://github.com/ytdl-org/youtube-dl wget pillow hachoir

      - name: 🏃‍♂️ Run the UserClient. 🏃‍♂️

        run: |

          python3 -m bot
